from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from services.document import extract_text_from_document
from services.nlp import *
from services.llm import generate_scorecard

router = APIRouter()

@router.post("/")
async def analyze_resume(
    file: UploadFile = File(...),
    jd: str = Form(...),
    role: str = Form(...),
    github: str = Form(""),
):
    """
    Core endpoint that takes a PDF resume, job description, target role, and optional GitHub URL.
    Returns a highly accurate JSON scorecard generated by the AI Engine.
    """
    if not file.filename.lower().endswith(('.pdf', '.doc', '.docx', '.txt')):
        raise HTTPException(status_code=400, detail="Only PDF, DOCX, and TXT files are supported.")
        
    try:
        # 1. Read and parse PDF
        file_bytes = await file.read()
        resume_text = extract_text_from_document(file_bytes, file.filename)
        
        if not resume_text or len(resume_text.strip()) < 50:
            raise HTTPException(status_code=400, detail="Could not extract enough text from the provided file.")

        # 2. LLM Deep Analysis (Groq LLaMA 3 70b)
        # We rely 100% on the LLM to provide the match_percentage and analysis
        # to prevent memory crashes (OOM) on free hosting tiers.
        scorecard = generate_scorecard(resume_text, jd, role)
        
        return {
            "status": "success",
            "message": "AI analysis complete.",
            "data": scorecard
        }
    except Exception as e:
        print(f"Error processing analysis: {str(e)}")
        raise HTTPException(status_code=500, detail=f"An error occurred during analysis: {str(e)}")
