from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from services.pdf import extract_text_from_pdf
from services.nlp import calculate_semantic_similarity, extract_keywords
from services.llm import generate_scorecard

router = APIRouter()

@router.post("/")
async def analyze_resume(
    file: UploadFile = File(...),
    jd: str = Form(...),
    role: str = Form(...),
    github: str = Form(""),
):
    """
    Core endpoint that takes a PDF resume, job description, target role, and optional GitHub URL.
    Returns a highly accurate JSON scorecard generated by the AI Engine.
    """
    if not file.filename.endswith(('.pdf', '.doc', '.docx')):
        raise HTTPException(status_code=400, detail="Only PDF and DOCX files are supported.")
        
    try:
        # 1. Read and parse PDF
        file_bytes = await file.read()
        resume_text = extract_text_from_pdf(file_bytes)
        
        if not resume_text or len(resume_text.strip()) < 50:
            raise HTTPException(status_code=400, detail="Could not extract enough text from the provided file.")

        # 2. Advanced NLP Embeddings (Semantic Match)
        semantic_score = calculate_semantic_similarity(resume_text, jd)
        
        # 3. LLM Deep Analysis (Groq LLaMA 3 70b)
        scorecard = generate_scorecard(resume_text, jd, role)
        
        # Override the LLM's guessed match_percentage with our mathematically accurate semantic score
        # But we blend them or use the LLM's component scores. We will use semantic_score as the main ATS score.
        scorecard["match_percentage"] = semantic_score
        
        return {
            "status": "success",
            "message": "AI analysis complete.",
            "data": scorecard
        }
    except Exception as e:
        print(f"Error processing analysis: {str(e)}")
        raise HTTPException(status_code=500, detail=f"An error occurred during analysis: {str(e)}")
